CUDA_VISIBLE_DEVICES=0 python main.py --task segmentation --gpus 0 --setname SpermSeg --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name aspcp --seg_feature_guide 2 --fg_start_stage 1 --fg_resize_stage 0 --fg_bottle_se 1 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth
### fg start stage
CUDA_VISIBLE_DEVICES=0 python main.py --task segmentation --gpus 0 --setname SpermSeg --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name aspcp --seg_feature_guide 2 --fg_start_stage 2 --fg_resize_stage 0 --fg_bottle_se 1 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth &
CUDA_VISIBLE_DEVICES=0 python main.py --task segmentation --gpus 0 --setname SpermSeg --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name aspcp --seg_feature_guide 2 --fg_start_stage 3 --fg_resize_stage 0 --fg_bottle_se 1 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth &
CUDA_VISIBLE_DEVICES=0 python main.py --task segmentation --gpus 0 --setname SpermSeg --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name aspcp --seg_feature_guide 2 --fg_start_stage 4 --fg_resize_stage 0 --fg_bottle_se 1 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth 
### se layer
CUDA_VISIBLE_DEVICES=0 python main.py --task segmentation --gpus 0 --setname SpermSeg --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name aspcp --seg_feature_guide 2 --fg_start_stage 1 --fg_resize_stage 0 --fg_bottle_se 0 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth
### resize stage
CUDA_VISIBLE_DEVICES=0 python main.py --task segmentation --gpus 0 --setname SpermSeg --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name aspcp --seg_feature_guide 2 --fg_start_stage 1 --fg_resize_stage 1 --fg_bottle_se 1 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth &&
CUDA_VISIBLE_DEVICES=0 python main.py --task segmentation --gpus 0 --setname SpermSeg --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name aspcp --seg_feature_guide 2 --fg_start_stage 1 --fg_resize_stage 2 --fg_bottle_se 1 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth &&
CUDA_VISIBLE_DEVICES=0 python main.py --task segmentation --gpus 0 --setname SpermSeg --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name aspcp --seg_feature_guide 2 --fg_start_stage 1 --fg_resize_stage 3 --fg_bottle_se 1 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth &&
CUDA_VISIBLE_DEVICES=0 python main.py --task segmentation --gpus 0 --setname SpermSeg --num_repeat 3 --num_workers 2 --epochs 100 --save_point None --batch_size 4 --lr 1e-6 --warmup_init_lr 5e-5 --max_lr 5e-4 --model_name resnet50 --sup_method common --optim adamw --weight_decay 0.03 --seg_head_name aspcp --seg_feature_guide 2 --fg_start_stage 1 --fg_resize_stage -1 --fg_bottle_se 1 --pretrained 2 --freeze_weight 3 --weight_name resnet50-2.pth